version: "3"
services:
  api:
    container_name: api
    build: ./
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - /Users/shaharlevy/data-general/git-repos/birman_project:/project


  mysql:
    container_name: mysql
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"

  rabbit:
    container_name: rabbit
    image: bitnami/rabbitmq
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "5672:5672"
      - "15672:15672"