version: "3"
services:
  api:
    build: ./
    links:
      - mysql
    ports:
      - "5000:5000"
    volumes:
      - /home/gal/Desktop/project/jsonfile:/project/jsonfile

  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
